sys/Areas/Admin/Controllers/BKMembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
using sys.Filters;
using sys.Models;

namespace sys.Areas.Admin.Controllers
{
    [PermissionFilter]
    [Authorize]
    public class BKMembersController : Controller
    {
        private Membersql db = new Membersql();
        private const int PageSize = 10;
        // GET: Members
        public ActionResult Index(int? page)
        {
            if (!page.HasValue)
            {
                page = 0;
            }
            else
            {
                page--;//ToPagedList的pageIndex預設第一頁是0,第二頁是1，所以要-1才是真的頁面
            }
            return View(db.Members.ToList().ToPagedList((int)page, PageSize));
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            ViewBag.id = id;
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            //有用jquery-tree時用
            List<Permission> permission = db.Permissions.ToList();
            StringBuilder stringBuilder = new StringBuilder();
            getList(permission, stringBuilder);
            ViewBag.data = stringBuilder.ToString();
            return View();
        }

        public void getList(List<Permission> permission, StringBuilder stringBuilder)
        {
            foreach (var item in permission)
            {
                if (stringBuilder.ToString().IndexOf("{id:" + item.id) == -1)
                {
                    stringBuilder.Append("{id:" + item.id + ",text:'" + item.id + "." + item.PermissionName + "'");
                    if (permission.Where(x => x.Pid == item.id).Count() > 0)
                    {
                        stringBuilder.Append(",children:[");
                        var subP = permission.Where(x => x.Pid == item.id).ToList();
                        getList(subP, stringBuilder);
                        stringBuilder.Append("]");
                    }
                    stringBuilder.Append("},");
                }
            }
        }
        public void getList(List<Permission> permission, StringBuilder stringBuilder, string ownPermission)
        {
            foreach (var item in permission)
            {
                string check = "false";
                if (stringBuilder.ToString().IndexOf("{id:" + item.id) == -1)
                {
                    if (!string.IsNullOrEmpty(ownPermission))
                    {
                        if (ownPermission.IndexOf("," + item.id + ",") != -1)
                        {
                            check = "true";
                        }
                    }
                    else
                    {
                        check = "false";
                    }
                    stringBuilder.Append("{id:" + item.id + ",text:'" +item.id+"." +item.PermissionName + "'" + ",checked:" + check);
                    if (permission.Where(x => x.Pid == item.id).Count() > 0)
                    {
                        stringBuilder.Append(",children:[");
                        var subP = permission.Where(x => x.Pid == item.id).ToList();
                        getList(subP, stringBuilder, ownPermission);
                        stringBuilder.Append("]");
                    }
                    stringBuilder.Append("},");
                }

            }
        }
        // POST: Members/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Account,Password,PasswordSalt,Name,Gender,Email,Permission,Tel,initDate")] Member member, HttpPostedFileBase NewImg)
        {
            if (ModelState.IsValid)
            {
                if (NewImg != null)
                {
                    if (NewImg.ContentType.IndexOf("image", System.StringComparison.Ordinal) == -1)
                    {
                        ViewBag.Message = "照片型態錯誤!";
                        return View(member);
                    }

                    //取得副檔名
                    string extension = Path.GetExtension(NewImg.FileName);
                    //新檔案名稱
                    string fileName = String.Format("{0:yyyyMMddhhmmsss}{1}", DateTime.Now, extension);
                    string savedName = Path.Combine(Server.MapPath("/Admin/UploadFile/Img"), fileName);
                    NewImg.SaveAs(savedName);
                    member.Img = fileName;
                }
                else
                {
                    member.Img = "0.png";
                }
                //密碼加密
                string salt = Guid.NewGuid().ToString();
                member.Password = GenerateHashWithSalt(member.Password, salt);
                member.PasswordSalt = salt;
                member.initDate = DateTime.Now;
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<Permission> permission = db.Permissions.ToList();
            StringBuilder stringBuilder = new StringBuilder();
            getList(permission, stringBuilder);
            ViewBag.data = stringBuilder.ToString();

            return View(member);
        }
        public static string GenerateHashWithSalt(string password, string salt)
        {
            // merge password and salt together
            string sHashWithSalt = password + salt;
            // convert this merged value to a byte array
            byte[] saltedHashBytes = Encoding.UTF8.GetBytes(sHashWithSalt);
            // use hash algorithm to compute the hash
            HashAlgorithm algorithm = new SHA256Managed();
            // convert merged bytes to a hash as byte array
            byte[] hash = algorithm.ComputeHash(saltedHashBytes);
            // return the has as a base 64 encoded string
            return Convert.ToBase64String(hash);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            ViewBag.PWD = member.Password;
            ViewBag.salt = member.PasswordSalt;
            ViewBag.Img = member.Img;
            List<Permission> permission = db.Permissions.ToList();
            StringBuilder stringBuilder = new StringBuilder();
            string ownPermission = member.Permission;
            getList(permission, stringBuilder, ownPermission);
            ViewBag.data = stringBuilder.ToString();
            ViewBag.Permission = member.Permission;
            ViewBag.initDate = member.initDate;
            return View(member);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Account,Password,PasswordSalt,Name,Gender,Email,Permission,Tel,Img,initDate")] Member member, HttpPostedFileBase NewImg, string NewPassword)
        {
            ViewBag.PWD = member.Password;
            ViewBag.salt = member.PasswordSalt;
            ViewBag.Img = member.Img;
            List<Permission> permission = db.Permissions.ToList();
            StringBuilder stringBuilder = new StringBuilder();
            string ownPermission = member.Permission;
            getList(permission, stringBuilder, ownPermission);
            ViewBag.data = stringBuilder.ToString();
            ViewBag.Permission = member.Permission;
            ViewBag.initDate = member.initDate;
            if (ModelState.IsValid)
            {
                if (NewImg != null)
                {
                    if (NewImg.ContentType.IndexOf("image", System.StringComparison.Ordinal) == -1)
                    {
                        ViewBag.Message = "照片型態錯誤!";
                        return View(member);
                    }
                    //取得副檔名
                    string extension = Path.GetExtension(NewImg.FileName);
                    //新檔案名稱
                    string fileName = String.Format("{0:yyyyMMddhhmmsss}.{1}", DateTime.Now, extension);
                    string savedName = Path.Combine(Server.MapPath("/Admin/UploadFile/Img"), fileName);
                    NewImg.SaveAs(savedName);
                    member.Img = fileName;
                    ViewBag.Img = member.Img;
                }
                //密碼加密
                if (!string.IsNullOrEmpty(NewPassword))
                {
                    string salt = Guid.NewGuid().ToString();
                    member.Password = GenerateHashWithSalt(NewPassword, salt);
                    member.PasswordSalt = salt;
                    ViewBag.PWD = member.Password;
                    ViewBag.salt = member.PasswordSalt;
                }
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                //ViewBag.PWD = member.Password;
                //ViewBag.salt = member.PasswordSalt;
                //ViewBag.Img = member.Img;
                //List<Permission> permission = db.Permissions.ToList();
                //StringBuilder stringBuilder = new StringBuilder();
                //string ownPermission = member.Permission;
                //getList(permission, stringBuilder, ownPermission);
                //ViewBag.data = stringBuilder.ToString();

sys/Areas/Admin/Views/BKMembers/Create.cshtml
@using sys.Models
@model sys.Models.Member

@{
    ViewBag.Title = "新增帳號";
}

<h3>@ViewBag.Title</h3>

<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<link href="/Admin/dist/bootree.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/paper/bootstrap.min.css" rel="stylesheet" type="text/css" />

<script src="/Admin/dist/bootree.min.js" type="text/javascript"></script>


@using (Html.BeginForm("Create","BKMembers",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" ,required=""} })
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" ,required=""} })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" ,required=""} })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" ,required=""} })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="form-control" name="Img" id="Img"/>
                @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Permission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<Permission> permissionList = ViewBag.pArray;
                }
                @*@foreach (var item in permissionList)
                    {*@
                <div class="container">
                    <div class="row">
                        <div id="tree"></div>
                    </div>
                </div>

                <input type="hidden" id="Permission" name="Permission"/>
                @*<input id="@(item.id)"
                           type="checkbox"
                           value=",@(item.id)," />
                    <label for="@(item.id)">@item.PermissionName</label>*@
                @*if ((ViewBag.Permission).TryGet.IndexOf(item.id) > -1)
                    {
                        <input id="chk@(item)"
                               type="checkbox"
                               value="@item"
                               checked="checked"/>
                    }
                    else
                    {
                        <input id="chk@(item)"
                               type="checkbox"
                               value="@item"
                               />
                    }*@
                <br />
                @*}*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增員工帳號" class="btn btn-default" />
                <a href="~/Admin/BKMembers" class="btn btn-default" style="padding-left: 10px">取消</a>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
       
        var tree = $('#tree').tree({
            primaryKey: 'id',
            uiLibrary: 'bootstrap',
            dataSource: [
                @Html.Raw(ViewBag.data)
            ],
            checkboxes: true
        });
        tree.on('checkboxChange', function (e, $node, record, state) {
            var checkedIds = tree.getCheckedNodes();
            $('#Permission').val(','+checkedIds+',');
        });
        console.log(tree);
    });
</script>
<style>
    .formbyc {
        padding: 30px;
    }
</style>

sys/Areas/Admin/Views/BKMembers/Delete.cshtml
@model sys.Models.Member

@{
    ViewBag.Title = "刪除員工帳號";
}

<h3>@ViewBag.Title</h3>

<h4 style="color: brown">你確定要刪除此帳號嗎?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @{
                ViewBag.Img = Model.Img;
            }
            <img src="/Admin/UploadFile/Img/@ViewBag.Img">
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Permission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Permission)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color right">
            <input type="submit" value="刪除" class="btn btn-default" /> 
            <a href="~/Admin/BKMembers" class="btn btn-default" style="padding-left: 10px">取消</a>
        </div>
    }
</div>
<style>
    .right {
        margin-left: 180px;
    }
</style>

sys/Areas/Admin/Views/BKMembers/Details.cshtml
@model sys.Models.Member

@{
    ViewBag.Title = "員工帳號詳情";
}

<h3>@ViewBag.Title</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @{
                ViewBag.Img = Model.Img;
            }
            <img src="/Admin/UploadFile/Img/@ViewBag.Img">
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Permission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Permission)
        </dd>

    </dl>
</div>
<p>
    <div class="form-actions no-color right">
        <a href="~/Admin/BKMembers/Edit/@ViewBag.id " class="btn btn-default" style="padding-left: 10px">修改</a>
        <a href="~/Admin/BKMembers" class="btn btn-default" style="padding-left: 10px">取消</a>
    </div>
</p>
<style>
    .right {
        margin-left: 180px;
    }
</style>

sys/Areas/Admin/Views/BKMembers/Edit.cshtml
@model sys.Models.Member

@{
    ViewBag.Title = "修改會員資料";
}

<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<link href="/Admin/dist/bootree.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/paper/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="/Admin/dist/bootree.min.js" type="text/javascript"></script>

<h3>@ViewBag.Title</h3>
@using (Html.BeginForm("Create","BKMembers",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <input type="hidden" value="@ViewBag.initDate " name="initDate">
        <div class="form-group">
            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" ,required=""} })
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="password" name="NewPassword" class="form-control" />
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
            <input type="hidden" name="Password" value=@ViewBag.PWD />
            <input type="hidden" name="PasswordSalt" value=@ViewBag.salt />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" ,required=""} })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" ,required=""} })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="/Admin/UploadFile/Img/@ViewBag.Img" style="width: 100px">
                <input type="hidden" name="Img" value="@ViewBag.Img ">
                <input type="file" class="form-control" name="NewImg" id="NewImg" />
                @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Permission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="container">
                    <div class="row">
                        <div id="tree"></div>
                    </div>
                </div>
                <input type="hidden" id="Permission" name="Permission" value="@ViewBag.Permission " />
                <br />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
                <a href="~/Admin/BKMembers" class="btn btn-default" style="padding-left: 10px">取消</a>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {

        var tree = $('#tree').tree({
            primaryKey: 'id',
            uiLibrary: 'bootstrap',
            dataSource: [
                @Html.Raw(ViewBag.data)
            ],
            checkboxes: true
        });
        tree.on('checkboxChange', function (e, $node, record, state) {
            var checkedIds = tree.getCheckedNodes();
            $('#Permission').val(','+checkedIds+',');
        });
        console.log(tree);
    });
</script>
<style>
    .formbyc {
        padding: 20px;
    }

    .btn-block {
        width: 135px;
    }
</style>

sys/Areas/Admin/Views/BKMembers/Index.cshtml
@using MvcPaging
@model MvcPaging.IPagedList<sys.Models.Member>

@{
    ViewBag.Title = "員工帳號清單";
}

<h3>@ViewBag.Title</h3>

<p>
    <a href="/Admin/BKMembers/Create" class="btn btn-block btn-success">新增員工帳號</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Account)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Tel)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Account)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tel)
            </td>
            <td>
                @Html.ActionLink("修改", "Edit", new { id = item.Id }) |
                @Html.ActionLink("詳情", "Details", new { id = item.Id }) |
                @Html.ActionLink("刪除", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<div class="pager">
    @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount)
</div>
<style>
    .btn-block {
        width: 110px;
    }
</style>